/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QScrollArea>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QTimeEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QTimeEdit *timeEdit;
    QLabel *label;
    QPushButton *panierBtn;
    QLabel *label_2;
    QLabel *label_3;
    QTabWidget *tabWidget;
    QWidget *tab_1;
    QScrollArea *scrollArea_1;
    QWidget *scrollAreaWidgetContents;
    QLabel *label_6;
    QLabel *label_5;
    QLabel *label_4;
    QLabel *label_7;
    QTextEdit *pj_description;
    QLabel *label_8;
    QLabel *pj_picture;
    QLabel *pj_name;
    QLabel *pj_prix;
    QLabel *pj_calorie;
    QLabel *pj_note;
    QScrollArea *scrollArea_2;
    QWidget *scrollAreaWidgetContents_2;
    QLabel *label_9;
    QLabel *label_10;
    QPushButton *platdujour_addlike;
    QPushButton *platdujour_adddislike;
    QTextEdit *textEdit_7;
    QLabel *label_11;
    QLabel *label_12;
    QTextEdit *textEdit_8;
    QPushButton *pushButton_4;
    QScrollArea *scrollArea_list_platdujour;
    QWidget *scrollAreaWidget_list_platdujour;
    QWidget *tab_2;
    QScrollArea *scrollArea_4;
    QWidget *scrollAreaWidgetContents_6;
    QLabel *label_27;
    QLabel *label_28;
    QPushButton *entree_addlike;
    QPushButton *entree_adddislike;
    QTextEdit *textEdit_19;
    QLabel *label_29;
    QLabel *label_30;
    QTextEdit *textEdit_20;
    QPushButton *pushButton_10;
    QScrollArea *scrollArea_list_entree;
    QWidget *scrollAreaWidget_list_entree;
    QScrollArea *scrollArea_3;
    QWidget *scrollAreaWidgetContents_3;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QTextEdit *e_description;
    QLabel *label_17;
    QLabel *e_name;
    QLabel *e_prix;
    QLabel *e_calorie;
    QLabel *e_picture;
    QLabel *e_note;
    QWidget *tab_3;
    QScrollArea *scrollArea_5;
    QWidget *scrollAreaWidgetContents_4;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QTextEdit *p_description;
    QLabel *label_22;
    QLabel *p_name;
    QLabel *p_prix;
    QLabel *p_calorie;
    QLabel *p_picture;
    QLabel *p_note;
    QScrollArea *scrollArea_6;
    QWidget *scrollAreaWidgetContents_5;
    QLabel *label_23;
    QLabel *label_24;
    QPushButton *plat_addlike;
    QPushButton *plat_adddislike;
    QTextEdit *textEdit_17;
    QLabel *label_25;
    QLabel *label_26;
    QTextEdit *textEdit_18;
    QPushButton *pushButton_7;
    QScrollArea *scrollArea_list_plat;
    QWidget *scrollAreaWidget_list_plat;
    QWidget *tab_4;
    QScrollArea *scrollArea_7;
    QWidget *scrollAreaWidgetContents_7;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QTextEdit *d_description;
    QLabel *label_35;
    QLabel *d_name;
    QLabel *d_prix;
    QLabel *d_calorie;
    QLabel *d_picture;
    QLabel *d_note;
    QScrollArea *scrollArea_8;
    QWidget *scrollAreaWidgetContents_8;
    QLabel *label_36;
    QLabel *label_37;
    QPushButton *dessert_addlike;
    QPushButton *dessert_adddislike;
    QTextEdit *textEdit_25;
    QLabel *label_38;
    QLabel *label_39;
    QTextEdit *textEdit_26;
    QPushButton *pushButton_13;
    QScrollArea *scrollArea_list_dessert;
    QWidget *scrollAreaWidget_list_dessert;
    QWidget *tab_5;
    QScrollArea *scrollArea_9;
    QWidget *scrollAreaWidgetContents_9;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QTextEdit *b_description;
    QLabel *label_44;
    QLabel *b_name;
    QLabel *b_prix;
    QLabel *b_calorie;
    QLabel *b_picture;
    QLabel *b_note;
    QScrollArea *scrollArea_10;
    QWidget *scrollAreaWidgetContents_10;
    QLabel *label_45;
    QLabel *label_46;
    QPushButton *boisson_addlike;
    QPushButton *boisson_adddislike;
    QTextEdit *textEdit_31;
    QLabel *label_47;
    QLabel *label_48;
    QTextEdit *textEdit_32;
    QPushButton *pushButton_16;
    QScrollArea *scrollArea_list_boisson;
    QWidget *scrollAreaWidget_list_boisson;
    QLabel *nomPlatLbl;
    QLabel *sommeLbl;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(708, 479);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        timeEdit = new QTimeEdit(centralWidget);
        timeEdit->setObjectName(QStringLiteral("timeEdit"));
        timeEdit->setGeometry(QRect(420, 0, 118, 24));
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(40, 0, 101, 21));
        panierBtn = new QPushButton(centralWidget);
        panierBtn->setObjectName(QStringLiteral("panierBtn"));
        panierBtn->setGeometry(QRect(600, 430, 113, 32));
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(50, 440, 81, 16));
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(170, 440, 81, 16));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(0, 20, 771, 401));
        tab_1 = new QWidget();
        tab_1->setObjectName(QStringLiteral("tab_1"));
        scrollArea_1 = new QScrollArea(tab_1);
        scrollArea_1->setObjectName(QStringLiteral("scrollArea_1"));
        scrollArea_1->setGeometry(QRect(0, 0, 371, 371));
        scrollArea_1->setWidgetResizable(true);
        scrollAreaWidgetContents = new QWidget();
        scrollAreaWidgetContents->setObjectName(QStringLiteral("scrollAreaWidgetContents"));
        scrollAreaWidgetContents->setGeometry(QRect(0, 0, 369, 369));
        label_6 = new QLabel(scrollAreaWidgetContents);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 50, 51, 16));
        label_5 = new QLabel(scrollAreaWidgetContents);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 30, 31, 16));
        label_4 = new QLabel(scrollAreaWidgetContents);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(10, 10, 51, 16));
        label_7 = new QLabel(scrollAreaWidgetContents);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(10, 260, 81, 16));
        pj_description = new QTextEdit(scrollAreaWidgetContents);
        pj_description->setObjectName(QStringLiteral("pj_description"));
        pj_description->setGeometry(QRect(10, 280, 351, 79));
        label_8 = new QLabel(scrollAreaWidgetContents);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(10, 70, 51, 16));
        pj_picture = new QLabel(scrollAreaWidgetContents);
        pj_picture->setObjectName(QStringLiteral("pj_picture"));
        pj_picture->setGeometry(QRect(50, 90, 271, 171));
        pj_name = new QLabel(scrollAreaWidgetContents);
        pj_name->setObjectName(QStringLiteral("pj_name"));
        pj_name->setGeometry(QRect(50, 10, 151, 16));
        pj_prix = new QLabel(scrollAreaWidgetContents);
        pj_prix->setObjectName(QStringLiteral("pj_prix"));
        pj_prix->setGeometry(QRect(50, 30, 161, 16));
        pj_calorie = new QLabel(scrollAreaWidgetContents);
        pj_calorie->setObjectName(QStringLiteral("pj_calorie"));
        pj_calorie->setGeometry(QRect(60, 50, 201, 16));
        pj_note = new QLabel(scrollAreaWidgetContents);
        pj_note->setObjectName(QStringLiteral("pj_note"));
        pj_note->setGeometry(QRect(60, 70, 61, 15));
        scrollArea_1->setWidget(scrollAreaWidgetContents);
        scrollArea_2 = new QScrollArea(tab_1);
        scrollArea_2->setObjectName(QStringLiteral("scrollArea_2"));
        scrollArea_2->setGeometry(QRect(370, 0, 341, 371));
        scrollArea_2->setWidgetResizable(true);
        scrollAreaWidgetContents_2 = new QWidget();
        scrollAreaWidgetContents_2->setObjectName(QStringLiteral("scrollAreaWidgetContents_2"));
        scrollAreaWidgetContents_2->setGeometry(QRect(0, 0, 339, 369));
        label_9 = new QLabel(scrollAreaWidgetContents_2);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(10, 10, 81, 16));
        label_10 = new QLabel(scrollAreaWidgetContents_2);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(10, 30, 111, 16));
        platdujour_addlike = new QPushButton(scrollAreaWidgetContents_2);
        platdujour_addlike->setObjectName(QStringLiteral("platdujour_addlike"));
        platdujour_addlike->setGeometry(QRect(110, 0, 113, 32));
        platdujour_adddislike = new QPushButton(scrollAreaWidgetContents_2);
        platdujour_adddislike->setObjectName(QStringLiteral("platdujour_adddislike"));
        platdujour_adddislike->setGeometry(QRect(110, 20, 113, 32));
        textEdit_7 = new QTextEdit(scrollAreaWidgetContents_2);
        textEdit_7->setObjectName(QStringLiteral("textEdit_7"));
        textEdit_7->setGeometry(QRect(110, 60, 61, 16));
        label_11 = new QLabel(scrollAreaWidgetContents_2);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(60, 60, 51, 16));
        label_12 = new QLabel(scrollAreaWidgetContents_2);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(60, 80, 51, 16));
        textEdit_8 = new QTextEdit(scrollAreaWidgetContents_2);
        textEdit_8->setObjectName(QStringLiteral("textEdit_8"));
        textEdit_8->setGeometry(QRect(110, 80, 61, 16));
        pushButton_4 = new QPushButton(scrollAreaWidgetContents_2);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(190, 70, 21, 21));
        scrollArea_list_platdujour = new QScrollArea(scrollAreaWidgetContents_2);
        scrollArea_list_platdujour->setObjectName(QStringLiteral("scrollArea_list_platdujour"));
        scrollArea_list_platdujour->setGeometry(QRect(10, 109, 321, 251));
        scrollArea_list_platdujour->setWidgetResizable(true);
        scrollAreaWidget_list_platdujour = new QWidget();
        scrollAreaWidget_list_platdujour->setObjectName(QStringLiteral("scrollAreaWidget_list_platdujour"));
        scrollAreaWidget_list_platdujour->setGeometry(QRect(0, 0, 319, 249));
        scrollAreaWidget_list_platdujour->setLayoutDirection(Qt::LeftToRight);
        scrollArea_list_platdujour->setWidget(scrollAreaWidget_list_platdujour);
        scrollArea_2->setWidget(scrollAreaWidgetContents_2);
        tabWidget->addTab(tab_1, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        scrollArea_4 = new QScrollArea(tab_2);
        scrollArea_4->setObjectName(QStringLiteral("scrollArea_4"));
        scrollArea_4->setGeometry(QRect(370, 0, 341, 371));
        scrollArea_4->setWidgetResizable(true);
        scrollAreaWidgetContents_6 = new QWidget();
        scrollAreaWidgetContents_6->setObjectName(QStringLiteral("scrollAreaWidgetContents_6"));
        scrollAreaWidgetContents_6->setGeometry(QRect(0, 0, 339, 369));
        label_27 = new QLabel(scrollAreaWidgetContents_6);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(10, 10, 81, 16));
        label_28 = new QLabel(scrollAreaWidgetContents_6);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(10, 30, 111, 16));
        entree_addlike = new QPushButton(scrollAreaWidgetContents_6);
        entree_addlike->setObjectName(QStringLiteral("entree_addlike"));
        entree_addlike->setGeometry(QRect(110, 0, 113, 32));
        entree_adddislike = new QPushButton(scrollAreaWidgetContents_6);
        entree_adddislike->setObjectName(QStringLiteral("entree_adddislike"));
        entree_adddislike->setGeometry(QRect(110, 20, 113, 32));
        textEdit_19 = new QTextEdit(scrollAreaWidgetContents_6);
        textEdit_19->setObjectName(QStringLiteral("textEdit_19"));
        textEdit_19->setGeometry(QRect(110, 60, 61, 16));
        label_29 = new QLabel(scrollAreaWidgetContents_6);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(60, 60, 51, 16));
        label_30 = new QLabel(scrollAreaWidgetContents_6);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(60, 80, 51, 16));
        textEdit_20 = new QTextEdit(scrollAreaWidgetContents_6);
        textEdit_20->setObjectName(QStringLiteral("textEdit_20"));
        textEdit_20->setGeometry(QRect(110, 80, 61, 16));
        pushButton_10 = new QPushButton(scrollAreaWidgetContents_6);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(190, 70, 21, 21));
        scrollArea_list_entree = new QScrollArea(scrollAreaWidgetContents_6);
        scrollArea_list_entree->setObjectName(QStringLiteral("scrollArea_list_entree"));
        scrollArea_list_entree->setGeometry(QRect(10, 109, 321, 251));
        scrollArea_list_entree->setWidgetResizable(true);
        scrollAreaWidget_list_entree = new QWidget();
        scrollAreaWidget_list_entree->setObjectName(QStringLiteral("scrollAreaWidget_list_entree"));
        scrollAreaWidget_list_entree->setGeometry(QRect(0, 0, 319, 249));
        scrollArea_list_entree->setWidget(scrollAreaWidget_list_entree);
        scrollArea_4->setWidget(scrollAreaWidgetContents_6);
        scrollArea_3 = new QScrollArea(tab_2);
        scrollArea_3->setObjectName(QStringLiteral("scrollArea_3"));
        scrollArea_3->setGeometry(QRect(0, 0, 371, 371));
        scrollArea_3->setWidgetResizable(true);
        scrollAreaWidgetContents_3 = new QWidget();
        scrollAreaWidgetContents_3->setObjectName(QStringLiteral("scrollAreaWidgetContents_3"));
        scrollAreaWidgetContents_3->setGeometry(QRect(0, 0, 369, 369));
        label_13 = new QLabel(scrollAreaWidgetContents_3);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(10, 50, 51, 16));
        label_14 = new QLabel(scrollAreaWidgetContents_3);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(10, 30, 31, 16));
        label_15 = new QLabel(scrollAreaWidgetContents_3);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(10, 10, 51, 16));
        label_16 = new QLabel(scrollAreaWidgetContents_3);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(10, 260, 81, 16));
        e_description = new QTextEdit(scrollAreaWidgetContents_3);
        e_description->setObjectName(QStringLiteral("e_description"));
        e_description->setGeometry(QRect(10, 280, 351, 79));
        label_17 = new QLabel(scrollAreaWidgetContents_3);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(10, 70, 41, 16));
        e_name = new QLabel(scrollAreaWidgetContents_3);
        e_name->setObjectName(QStringLiteral("e_name"));
        e_name->setGeometry(QRect(50, 10, 61, 15));
        e_prix = new QLabel(scrollAreaWidgetContents_3);
        e_prix->setObjectName(QStringLiteral("e_prix"));
        e_prix->setGeometry(QRect(50, 30, 61, 15));
        e_calorie = new QLabel(scrollAreaWidgetContents_3);
        e_calorie->setObjectName(QStringLiteral("e_calorie"));
        e_calorie->setGeometry(QRect(60, 50, 61, 15));
        e_picture = new QLabel(scrollAreaWidgetContents_3);
        e_picture->setObjectName(QStringLiteral("e_picture"));
        e_picture->setGeometry(QRect(60, 100, 181, 151));
        e_note = new QLabel(scrollAreaWidgetContents_3);
        e_note->setObjectName(QStringLiteral("e_note"));
        e_note->setGeometry(QRect(60, 70, 61, 15));
        scrollArea_3->setWidget(scrollAreaWidgetContents_3);
        tabWidget->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        scrollArea_5 = new QScrollArea(tab_3);
        scrollArea_5->setObjectName(QStringLiteral("scrollArea_5"));
        scrollArea_5->setGeometry(QRect(0, 0, 371, 371));
        scrollArea_5->setWidgetResizable(true);
        scrollAreaWidgetContents_4 = new QWidget();
        scrollAreaWidgetContents_4->setObjectName(QStringLiteral("scrollAreaWidgetContents_4"));
        scrollAreaWidgetContents_4->setGeometry(QRect(0, 0, 369, 369));
        label_18 = new QLabel(scrollAreaWidgetContents_4);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(10, 50, 51, 16));
        label_19 = new QLabel(scrollAreaWidgetContents_4);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(10, 30, 51, 16));
        label_20 = new QLabel(scrollAreaWidgetContents_4);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(10, 10, 51, 16));
        label_21 = new QLabel(scrollAreaWidgetContents_4);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(10, 260, 81, 16));
        p_description = new QTextEdit(scrollAreaWidgetContents_4);
        p_description->setObjectName(QStringLiteral("p_description"));
        p_description->setGeometry(QRect(10, 280, 351, 79));
        label_22 = new QLabel(scrollAreaWidgetContents_4);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(10, 70, 51, 16));
        p_name = new QLabel(scrollAreaWidgetContents_4);
        p_name->setObjectName(QStringLiteral("p_name"));
        p_name->setGeometry(QRect(50, 10, 61, 15));
        p_prix = new QLabel(scrollAreaWidgetContents_4);
        p_prix->setObjectName(QStringLiteral("p_prix"));
        p_prix->setGeometry(QRect(50, 30, 61, 15));
        p_calorie = new QLabel(scrollAreaWidgetContents_4);
        p_calorie->setObjectName(QStringLiteral("p_calorie"));
        p_calorie->setGeometry(QRect(60, 50, 61, 15));
        p_picture = new QLabel(scrollAreaWidgetContents_4);
        p_picture->setObjectName(QStringLiteral("p_picture"));
        p_picture->setGeometry(QRect(60, 100, 181, 151));
        p_note = new QLabel(scrollAreaWidgetContents_4);
        p_note->setObjectName(QStringLiteral("p_note"));
        p_note->setGeometry(QRect(60, 70, 61, 15));
        scrollArea_5->setWidget(scrollAreaWidgetContents_4);
        scrollArea_6 = new QScrollArea(tab_3);
        scrollArea_6->setObjectName(QStringLiteral("scrollArea_6"));
        scrollArea_6->setGeometry(QRect(370, 0, 341, 371));
        scrollArea_6->setWidgetResizable(true);
        scrollAreaWidgetContents_5 = new QWidget();
        scrollAreaWidgetContents_5->setObjectName(QStringLiteral("scrollAreaWidgetContents_5"));
        scrollAreaWidgetContents_5->setGeometry(QRect(0, 0, 339, 369));
        label_23 = new QLabel(scrollAreaWidgetContents_5);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(10, 10, 81, 16));
        label_24 = new QLabel(scrollAreaWidgetContents_5);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(10, 30, 111, 16));
        plat_addlike = new QPushButton(scrollAreaWidgetContents_5);
        plat_addlike->setObjectName(QStringLiteral("plat_addlike"));
        plat_addlike->setGeometry(QRect(110, 0, 113, 32));
        plat_adddislike = new QPushButton(scrollAreaWidgetContents_5);
        plat_adddislike->setObjectName(QStringLiteral("plat_adddislike"));
        plat_adddislike->setGeometry(QRect(110, 20, 113, 32));
        textEdit_17 = new QTextEdit(scrollAreaWidgetContents_5);
        textEdit_17->setObjectName(QStringLiteral("textEdit_17"));
        textEdit_17->setGeometry(QRect(110, 60, 61, 16));
        label_25 = new QLabel(scrollAreaWidgetContents_5);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(60, 60, 51, 16));
        label_26 = new QLabel(scrollAreaWidgetContents_5);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(60, 80, 51, 16));
        textEdit_18 = new QTextEdit(scrollAreaWidgetContents_5);
        textEdit_18->setObjectName(QStringLiteral("textEdit_18"));
        textEdit_18->setGeometry(QRect(110, 80, 61, 16));
        pushButton_7 = new QPushButton(scrollAreaWidgetContents_5);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(190, 70, 21, 21));
        scrollArea_list_plat = new QScrollArea(scrollAreaWidgetContents_5);
        scrollArea_list_plat->setObjectName(QStringLiteral("scrollArea_list_plat"));
        scrollArea_list_plat->setGeometry(QRect(10, 109, 321, 251));
        scrollArea_list_plat->setWidgetResizable(true);
        scrollAreaWidget_list_plat = new QWidget();
        scrollAreaWidget_list_plat->setObjectName(QStringLiteral("scrollAreaWidget_list_plat"));
        scrollAreaWidget_list_plat->setGeometry(QRect(0, 0, 319, 249));
        scrollArea_list_plat->setWidget(scrollAreaWidget_list_plat);
        scrollArea_6->setWidget(scrollAreaWidgetContents_5);
        tabWidget->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        scrollArea_7 = new QScrollArea(tab_4);
        scrollArea_7->setObjectName(QStringLiteral("scrollArea_7"));
        scrollArea_7->setGeometry(QRect(0, 0, 371, 371));
        scrollArea_7->setWidgetResizable(true);
        scrollAreaWidgetContents_7 = new QWidget();
        scrollAreaWidgetContents_7->setObjectName(QStringLiteral("scrollAreaWidgetContents_7"));
        scrollAreaWidgetContents_7->setGeometry(QRect(0, 0, 369, 369));
        label_31 = new QLabel(scrollAreaWidgetContents_7);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(10, 50, 51, 16));
        label_32 = new QLabel(scrollAreaWidgetContents_7);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(10, 30, 51, 16));
        label_33 = new QLabel(scrollAreaWidgetContents_7);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(10, 10, 51, 16));
        label_34 = new QLabel(scrollAreaWidgetContents_7);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(10, 260, 81, 16));
        d_description = new QTextEdit(scrollAreaWidgetContents_7);
        d_description->setObjectName(QStringLiteral("d_description"));
        d_description->setGeometry(QRect(10, 280, 351, 79));
        label_35 = new QLabel(scrollAreaWidgetContents_7);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(10, 70, 51, 16));
        d_name = new QLabel(scrollAreaWidgetContents_7);
        d_name->setObjectName(QStringLiteral("d_name"));
        d_name->setGeometry(QRect(50, 10, 61, 15));
        d_prix = new QLabel(scrollAreaWidgetContents_7);
        d_prix->setObjectName(QStringLiteral("d_prix"));
        d_prix->setGeometry(QRect(50, 30, 61, 15));
        d_calorie = new QLabel(scrollAreaWidgetContents_7);
        d_calorie->setObjectName(QStringLiteral("d_calorie"));
        d_calorie->setGeometry(QRect(60, 50, 61, 15));
        d_picture = new QLabel(scrollAreaWidgetContents_7);
        d_picture->setObjectName(QStringLiteral("d_picture"));
        d_picture->setGeometry(QRect(30, 90, 261, 161));
        d_note = new QLabel(scrollAreaWidgetContents_7);
        d_note->setObjectName(QStringLiteral("d_note"));
        d_note->setGeometry(QRect(50, 70, 61, 15));
        scrollArea_7->setWidget(scrollAreaWidgetContents_7);
        scrollArea_8 = new QScrollArea(tab_4);
        scrollArea_8->setObjectName(QStringLiteral("scrollArea_8"));
        scrollArea_8->setGeometry(QRect(370, 0, 341, 371));
        scrollArea_8->setWidgetResizable(true);
        scrollAreaWidgetContents_8 = new QWidget();
        scrollAreaWidgetContents_8->setObjectName(QStringLiteral("scrollAreaWidgetContents_8"));
        scrollAreaWidgetContents_8->setGeometry(QRect(0, 0, 339, 369));
        label_36 = new QLabel(scrollAreaWidgetContents_8);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(10, 10, 81, 16));
        label_37 = new QLabel(scrollAreaWidgetContents_8);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(10, 30, 111, 16));
        dessert_addlike = new QPushButton(scrollAreaWidgetContents_8);
        dessert_addlike->setObjectName(QStringLiteral("dessert_addlike"));
        dessert_addlike->setGeometry(QRect(110, 0, 113, 32));
        dessert_adddislike = new QPushButton(scrollAreaWidgetContents_8);
        dessert_adddislike->setObjectName(QStringLiteral("dessert_adddislike"));
        dessert_adddislike->setGeometry(QRect(110, 20, 113, 32));
        textEdit_25 = new QTextEdit(scrollAreaWidgetContents_8);
        textEdit_25->setObjectName(QStringLiteral("textEdit_25"));
        textEdit_25->setGeometry(QRect(110, 60, 61, 16));
        label_38 = new QLabel(scrollAreaWidgetContents_8);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(60, 60, 51, 16));
        label_39 = new QLabel(scrollAreaWidgetContents_8);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(60, 80, 51, 16));
        textEdit_26 = new QTextEdit(scrollAreaWidgetContents_8);
        textEdit_26->setObjectName(QStringLiteral("textEdit_26"));
        textEdit_26->setGeometry(QRect(110, 80, 61, 16));
        pushButton_13 = new QPushButton(scrollAreaWidgetContents_8);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(190, 70, 21, 21));
        scrollArea_list_dessert = new QScrollArea(scrollAreaWidgetContents_8);
        scrollArea_list_dessert->setObjectName(QStringLiteral("scrollArea_list_dessert"));
        scrollArea_list_dessert->setGeometry(QRect(10, 109, 321, 251));
        scrollArea_list_dessert->setWidgetResizable(true);
        scrollAreaWidget_list_dessert = new QWidget();
        scrollAreaWidget_list_dessert->setObjectName(QStringLiteral("scrollAreaWidget_list_dessert"));
        scrollAreaWidget_list_dessert->setGeometry(QRect(0, 0, 319, 249));
        scrollArea_list_dessert->setWidget(scrollAreaWidget_list_dessert);
        scrollArea_8->setWidget(scrollAreaWidgetContents_8);
        tabWidget->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        scrollArea_9 = new QScrollArea(tab_5);
        scrollArea_9->setObjectName(QStringLiteral("scrollArea_9"));
        scrollArea_9->setGeometry(QRect(0, 0, 371, 371));
        scrollArea_9->setWidgetResizable(true);
        scrollAreaWidgetContents_9 = new QWidget();
        scrollAreaWidgetContents_9->setObjectName(QStringLiteral("scrollAreaWidgetContents_9"));
        scrollAreaWidgetContents_9->setGeometry(QRect(0, 0, 369, 369));
        label_40 = new QLabel(scrollAreaWidgetContents_9);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(10, 50, 51, 16));
        label_41 = new QLabel(scrollAreaWidgetContents_9);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(10, 30, 51, 16));
        label_42 = new QLabel(scrollAreaWidgetContents_9);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(10, 10, 51, 16));
        label_43 = new QLabel(scrollAreaWidgetContents_9);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(10, 260, 81, 16));
        b_description = new QTextEdit(scrollAreaWidgetContents_9);
        b_description->setObjectName(QStringLiteral("b_description"));
        b_description->setGeometry(QRect(10, 280, 351, 79));
        label_44 = new QLabel(scrollAreaWidgetContents_9);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(10, 70, 51, 16));
        b_name = new QLabel(scrollAreaWidgetContents_9);
        b_name->setObjectName(QStringLiteral("b_name"));
        b_name->setGeometry(QRect(50, 10, 61, 15));
        b_prix = new QLabel(scrollAreaWidgetContents_9);
        b_prix->setObjectName(QStringLiteral("b_prix"));
        b_prix->setGeometry(QRect(50, 30, 61, 15));
        b_calorie = new QLabel(scrollAreaWidgetContents_9);
        b_calorie->setObjectName(QStringLiteral("b_calorie"));
        b_calorie->setGeometry(QRect(60, 50, 61, 15));
        b_picture = new QLabel(scrollAreaWidgetContents_9);
        b_picture->setObjectName(QStringLiteral("b_picture"));
        b_picture->setGeometry(QRect(10, 90, 221, 161));
        b_note = new QLabel(scrollAreaWidgetContents_9);
        b_note->setObjectName(QStringLiteral("b_note"));
        b_note->setGeometry(QRect(50, 70, 61, 15));
        scrollArea_9->setWidget(scrollAreaWidgetContents_9);
        scrollArea_10 = new QScrollArea(tab_5);
        scrollArea_10->setObjectName(QStringLiteral("scrollArea_10"));
        scrollArea_10->setGeometry(QRect(370, 0, 341, 371));
        scrollArea_10->setWidgetResizable(true);
        scrollAreaWidgetContents_10 = new QWidget();
        scrollAreaWidgetContents_10->setObjectName(QStringLiteral("scrollAreaWidgetContents_10"));
        scrollAreaWidgetContents_10->setGeometry(QRect(0, 0, 339, 369));
        label_45 = new QLabel(scrollAreaWidgetContents_10);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(10, 10, 81, 16));
        label_46 = new QLabel(scrollAreaWidgetContents_10);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(10, 30, 111, 16));
        boisson_addlike = new QPushButton(scrollAreaWidgetContents_10);
        boisson_addlike->setObjectName(QStringLiteral("boisson_addlike"));
        boisson_addlike->setGeometry(QRect(110, 0, 113, 32));
        boisson_adddislike = new QPushButton(scrollAreaWidgetContents_10);
        boisson_adddislike->setObjectName(QStringLiteral("boisson_adddislike"));
        boisson_adddislike->setGeometry(QRect(110, 20, 113, 32));
        textEdit_31 = new QTextEdit(scrollAreaWidgetContents_10);
        textEdit_31->setObjectName(QStringLiteral("textEdit_31"));
        textEdit_31->setGeometry(QRect(110, 60, 61, 16));
        label_47 = new QLabel(scrollAreaWidgetContents_10);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(60, 60, 51, 16));
        label_48 = new QLabel(scrollAreaWidgetContents_10);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(60, 80, 51, 16));
        textEdit_32 = new QTextEdit(scrollAreaWidgetContents_10);
        textEdit_32->setObjectName(QStringLiteral("textEdit_32"));
        textEdit_32->setGeometry(QRect(110, 80, 61, 16));
        pushButton_16 = new QPushButton(scrollAreaWidgetContents_10);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(190, 70, 21, 21));
        scrollArea_list_boisson = new QScrollArea(scrollAreaWidgetContents_10);
        scrollArea_list_boisson->setObjectName(QStringLiteral("scrollArea_list_boisson"));
        scrollArea_list_boisson->setGeometry(QRect(9, 109, 321, 251));
        scrollArea_list_boisson->setWidgetResizable(true);
        scrollAreaWidget_list_boisson = new QWidget();
        scrollAreaWidget_list_boisson->setObjectName(QStringLiteral("scrollAreaWidget_list_boisson"));
        scrollAreaWidget_list_boisson->setGeometry(QRect(0, 0, 319, 249));
        scrollArea_list_boisson->setWidget(scrollAreaWidget_list_boisson);
        scrollArea_10->setWidget(scrollAreaWidgetContents_10);
        tabWidget->addTab(tab_5, QString());
        nomPlatLbl = new QLabel(centralWidget);
        nomPlatLbl->setObjectName(QStringLiteral("nomPlatLbl"));
        nomPlatLbl->setGeometry(QRect(20, 440, 31, 16));
        sommeLbl = new QLabel(centralWidget);
        sommeLbl->setObjectName(QStringLiteral("sommeLbl"));
        sommeLbl->setGeometry(QRect(140, 440, 31, 16));
        MainWindow->setCentralWidget(centralWidget);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0));
        label->setText(QApplication::translate("MainWindow", "Bienvenue\357\274\201", 0));
        panierBtn->setText(QApplication::translate("MainWindow", "Panier", 0));
        label_2->setText(QApplication::translate("MainWindow", "plats choisis", 0));
        label_3->setText(QApplication::translate("MainWindow", "euros", 0));
        label_6->setText(QApplication::translate("MainWindow", "Calorie:", 0));
        label_5->setText(QApplication::translate("MainWindow", "Prix:", 0));
        label_4->setText(QApplication::translate("MainWindow", "Nom:", 0));
        label_7->setText(QApplication::translate("MainWindow", "Description:", 0));
        label_8->setText(QApplication::translate("MainWindow", "Note:", 0));
        pj_picture->setText(QApplication::translate("MainWindow", "picture to be put here", 0));
        pj_name->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        pj_prix->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        pj_calorie->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        pj_note->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        label_9->setText(QApplication::translate("MainWindow", "P\303\251r\303\251rence:", 0));
        label_10->setText(QApplication::translate("MainWindow", "Ne mange pas:", 0));
        platdujour_addlike->setText(QApplication::translate("MainWindow", "+Ajouter", 0));
        platdujour_adddislike->setText(QApplication::translate("MainWindow", "+Ajouter", 0));
        label_11->setText(QApplication::translate("MainWindow", "Nom:", 0));
        label_12->setText(QApplication::translate("MainWindow", "\303\251toiles:", 0));
        pushButton_4->setText(QApplication::translate("MainWindow", "+", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_1), QApplication::translate("MainWindow", "plat du jour", 0));
        label_27->setText(QApplication::translate("MainWindow", "P\303\251r\303\251rence:", 0));
        label_28->setText(QApplication::translate("MainWindow", "Ne mange pas:", 0));
        entree_addlike->setText(QApplication::translate("MainWindow", "+Ajouter", 0));
        entree_adddislike->setText(QApplication::translate("MainWindow", "+Ajouter", 0));
        label_29->setText(QApplication::translate("MainWindow", "Nom:", 0));
        label_30->setText(QApplication::translate("MainWindow", "\303\251toiles:", 0));
        pushButton_10->setText(QApplication::translate("MainWindow", "+", 0));
        label_13->setText(QApplication::translate("MainWindow", "Calorie:", 0));
        label_14->setText(QApplication::translate("MainWindow", "Prix:", 0));
        label_15->setText(QApplication::translate("MainWindow", "Nom:", 0));
        label_16->setText(QApplication::translate("MainWindow", "Description:", 0));
        label_17->setText(QApplication::translate("MainWindow", "Note:", 0));
        e_name->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        e_prix->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        e_calorie->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        e_picture->setText(QApplication::translate("MainWindow", "Picture to be put here", 0));
        e_note->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "entr\303\251e", 0));
        label_18->setText(QApplication::translate("MainWindow", "Calorie:", 0));
        label_19->setText(QApplication::translate("MainWindow", "Prix:", 0));
        label_20->setText(QApplication::translate("MainWindow", "Nom:", 0));
        label_21->setText(QApplication::translate("MainWindow", "Description:", 0));
        label_22->setText(QApplication::translate("MainWindow", "Note:", 0));
        p_name->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        p_prix->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        p_calorie->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        p_picture->setText(QApplication::translate("MainWindow", "Picture to be put here", 0));
        p_note->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        label_23->setText(QApplication::translate("MainWindow", "P\303\251r\303\251rence:", 0));
        label_24->setText(QApplication::translate("MainWindow", "Ne mange pas:", 0));
        plat_addlike->setText(QApplication::translate("MainWindow", "+Ajouter", 0));
        plat_adddislike->setText(QApplication::translate("MainWindow", "+Ajouter", 0));
        label_25->setText(QApplication::translate("MainWindow", "Nom:", 0));
        label_26->setText(QApplication::translate("MainWindow", "\303\251toiles:", 0));
        pushButton_7->setText(QApplication::translate("MainWindow", "+", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("MainWindow", "plat", 0));
        label_31->setText(QApplication::translate("MainWindow", "Calorie:", 0));
        label_32->setText(QApplication::translate("MainWindow", "Prix", 0));
        label_33->setText(QApplication::translate("MainWindow", "Nom:", 0));
        label_34->setText(QApplication::translate("MainWindow", "Description:", 0));
        label_35->setText(QApplication::translate("MainWindow", "Note:", 0));
        d_name->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        d_prix->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        d_calorie->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        d_picture->setText(QApplication::translate("MainWindow", "Picture to be put here", 0));
        d_note->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        label_36->setText(QApplication::translate("MainWindow", "P\303\251r\303\251rence:", 0));
        label_37->setText(QApplication::translate("MainWindow", "Ne mange pas:", 0));
        dessert_addlike->setText(QApplication::translate("MainWindow", "+Ajouter", 0));
        dessert_adddislike->setText(QApplication::translate("MainWindow", "+Ajouter", 0));
        label_38->setText(QApplication::translate("MainWindow", "Nom:", 0));
        label_39->setText(QApplication::translate("MainWindow", "\303\251toiles:", 0));
        pushButton_13->setText(QApplication::translate("MainWindow", "+", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("MainWindow", "dessert", 0));
        label_40->setText(QApplication::translate("MainWindow", "Calorie:", 0));
        label_41->setText(QApplication::translate("MainWindow", "Prix", 0));
        label_42->setText(QApplication::translate("MainWindow", "Nom:", 0));
        label_43->setText(QApplication::translate("MainWindow", "Description:", 0));
        label_44->setText(QApplication::translate("MainWindow", "Note:", 0));
        b_name->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        b_prix->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        b_calorie->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        b_picture->setText(QApplication::translate("MainWindow", "Picture to be put here.", 0));
        b_note->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        label_45->setText(QApplication::translate("MainWindow", "P\303\251r\303\251rence:", 0));
        label_46->setText(QApplication::translate("MainWindow", "Ne mange pas:", 0));
        boisson_addlike->setText(QApplication::translate("MainWindow", "+Ajouter", 0));
        boisson_adddislike->setText(QApplication::translate("MainWindow", "+Ajouter", 0));
        label_47->setText(QApplication::translate("MainWindow", "Nom:", 0));
        label_48->setText(QApplication::translate("MainWindow", "\303\251toiles:", 0));
        pushButton_16->setText(QApplication::translate("MainWindow", "+", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QApplication::translate("MainWindow", "Boisson", 0));
        nomPlatLbl->setText(QApplication::translate("MainWindow", "0", 0));
        sommeLbl->setText(QApplication::translate("MainWindow", "0", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
