/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QScrollArea>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QTimeEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QTimeEdit *timeEdit;
    QLabel *label;
    QPushButton *pushButton;
    QLabel *label_2;
    QTextEdit *textEdit_2;
    QLabel *label_3;
    QTabWidget *tabWidget;
    QWidget *tab_1;
    QScrollArea *scrollArea;
    QWidget *scrollAreaWidgetContents;
    QLabel *label_6;
    QLabel *label_5;
    QLabel *label_4;
    QTextEdit *textEdit_3;
    QTextEdit *textEdit;
    QTextEdit *textEdit_4;
    QLabel *label_7;
    QTextEdit *textEdit_5;
    QLabel *label_8;
    QScrollArea *scrollArea_2;
    QWidget *scrollAreaWidgetContents_2;
    QLabel *label_9;
    QLabel *label_10;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QTextEdit *textEdit_7;
    QLabel *label_11;
    QLabel *label_12;
    QTextEdit *textEdit_8;
    QPushButton *pushButton_4;
    QWidget *tab_2;
    QScrollArea *scrollArea_6;
    QWidget *scrollAreaWidgetContents_6;
    QLabel *label_27;
    QLabel *label_28;
    QPushButton *pushButton_8;
    QPushButton *pushButton_9;
    QTextEdit *textEdit_19;
    QLabel *label_29;
    QLabel *label_30;
    QTextEdit *textEdit_20;
    QPushButton *pushButton_10;
    QScrollArea *scrollArea_3;
    QWidget *scrollAreaWidgetContents_3;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QTextEdit *textEdit_9;
    QTextEdit *textEdit_10;
    QTextEdit *textEdit_11;
    QLabel *label_16;
    QTextEdit *textEdit_12;
    QLabel *label_17;
    QWidget *tab_3;
    QScrollArea *scrollArea_4;
    QWidget *scrollAreaWidgetContents_4;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QTextEdit *textEdit_13;
    QTextEdit *textEdit_14;
    QTextEdit *textEdit_15;
    QLabel *label_21;
    QTextEdit *textEdit_16;
    QLabel *label_22;
    QScrollArea *scrollArea_5;
    QWidget *scrollAreaWidgetContents_5;
    QLabel *label_23;
    QLabel *label_24;
    QPushButton *pushButton_5;
    QPushButton *pushButton_6;
    QTextEdit *textEdit_17;
    QLabel *label_25;
    QLabel *label_26;
    QTextEdit *textEdit_18;
    QPushButton *pushButton_7;
    QWidget *tab_4;
    QScrollArea *scrollArea_7;
    QWidget *scrollAreaWidgetContents_7;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QTextEdit *textEdit_21;
    QTextEdit *textEdit_22;
    QTextEdit *textEdit_23;
    QLabel *label_34;
    QTextEdit *textEdit_24;
    QLabel *label_35;
    QScrollArea *scrollArea_8;
    QWidget *scrollAreaWidgetContents_8;
    QLabel *label_36;
    QLabel *label_37;
    QPushButton *pushButton_11;
    QPushButton *pushButton_12;
    QTextEdit *textEdit_25;
    QLabel *label_38;
    QLabel *label_39;
    QTextEdit *textEdit_26;
    QPushButton *pushButton_13;
    QWidget *tab_5;
    QScrollArea *scrollArea_9;
    QWidget *scrollAreaWidgetContents_9;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QTextEdit *textEdit_27;
    QTextEdit *textEdit_28;
    QTextEdit *textEdit_29;
    QLabel *label_43;
    QTextEdit *textEdit_30;
    QLabel *label_44;
    QScrollArea *scrollArea_10;
    QWidget *scrollAreaWidgetContents_10;
    QLabel *label_45;
    QLabel *label_46;
    QPushButton *pushButton_14;
    QPushButton *pushButton_15;
    QTextEdit *textEdit_31;
    QLabel *label_47;
    QLabel *label_48;
    QTextEdit *textEdit_32;
    QPushButton *pushButton_16;
    QTextEdit *textEdit_6;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(708, 479);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        timeEdit = new QTimeEdit(centralWidget);
        timeEdit->setObjectName(QStringLiteral("timeEdit"));
        timeEdit->setGeometry(QRect(420, 0, 118, 24));
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(40, 0, 101, 21));
        pushButton = new QPushButton(centralWidget);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(600, 430, 113, 32));
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(50, 440, 81, 16));
        textEdit_2 = new QTextEdit(centralWidget);
        textEdit_2->setObjectName(QStringLiteral("textEdit_2"));
        textEdit_2->setGeometry(QRect(130, 440, 31, 16));
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(170, 440, 81, 16));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(0, 30, 771, 401));
        tab_1 = new QWidget();
        tab_1->setObjectName(QStringLiteral("tab_1"));
        scrollArea = new QScrollArea(tab_1);
        scrollArea->setObjectName(QStringLiteral("scrollArea"));
        scrollArea->setGeometry(QRect(0, 0, 371, 371));
        scrollArea->setWidgetResizable(true);
        scrollAreaWidgetContents = new QWidget();
        scrollAreaWidgetContents->setObjectName(QStringLiteral("scrollAreaWidgetContents"));
        scrollAreaWidgetContents->setGeometry(QRect(0, 0, 369, 369));
        label_6 = new QLabel(scrollAreaWidgetContents);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(170, 50, 51, 16));
        label_5 = new QLabel(scrollAreaWidgetContents);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(170, 30, 51, 16));
        label_4 = new QLabel(scrollAreaWidgetContents);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(170, 10, 51, 16));
        textEdit_3 = new QTextEdit(scrollAreaWidgetContents);
        textEdit_3->setObjectName(QStringLiteral("textEdit_3"));
        textEdit_3->setGeometry(QRect(220, 10, 61, 16));
        textEdit = new QTextEdit(scrollAreaWidgetContents);
        textEdit->setObjectName(QStringLiteral("textEdit"));
        textEdit->setGeometry(QRect(220, 30, 61, 16));
        textEdit_4 = new QTextEdit(scrollAreaWidgetContents);
        textEdit_4->setObjectName(QStringLiteral("textEdit_4"));
        textEdit_4->setGeometry(QRect(220, 50, 61, 16));
        label_7 = new QLabel(scrollAreaWidgetContents);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(20, 90, 81, 16));
        textEdit_5 = new QTextEdit(scrollAreaWidgetContents);
        textEdit_5->setObjectName(QStringLiteral("textEdit_5"));
        textEdit_5->setGeometry(QRect(0, 120, 301, 79));
        label_8 = new QLabel(scrollAreaWidgetContents);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(10, 210, 51, 16));
        scrollArea->setWidget(scrollAreaWidgetContents);
        scrollArea_2 = new QScrollArea(tab_1);
        scrollArea_2->setObjectName(QStringLiteral("scrollArea_2"));
        scrollArea_2->setGeometry(QRect(370, 0, 341, 371));
        scrollArea_2->setWidgetResizable(true);
        scrollAreaWidgetContents_2 = new QWidget();
        scrollAreaWidgetContents_2->setObjectName(QStringLiteral("scrollAreaWidgetContents_2"));
        scrollAreaWidgetContents_2->setGeometry(QRect(0, 0, 339, 369));
        label_9 = new QLabel(scrollAreaWidgetContents_2);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(10, 10, 81, 16));
        label_10 = new QLabel(scrollAreaWidgetContents_2);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(10, 30, 111, 16));
        pushButton_2 = new QPushButton(scrollAreaWidgetContents_2);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(110, 0, 113, 32));
        pushButton_3 = new QPushButton(scrollAreaWidgetContents_2);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(110, 20, 113, 32));
        textEdit_7 = new QTextEdit(scrollAreaWidgetContents_2);
        textEdit_7->setObjectName(QStringLiteral("textEdit_7"));
        textEdit_7->setGeometry(QRect(110, 60, 61, 16));
        label_11 = new QLabel(scrollAreaWidgetContents_2);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(60, 60, 51, 16));
        label_12 = new QLabel(scrollAreaWidgetContents_2);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(60, 80, 51, 16));
        textEdit_8 = new QTextEdit(scrollAreaWidgetContents_2);
        textEdit_8->setObjectName(QStringLiteral("textEdit_8"));
        textEdit_8->setGeometry(QRect(110, 80, 61, 16));
        pushButton_4 = new QPushButton(scrollAreaWidgetContents_2);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(190, 70, 21, 21));
        scrollArea_2->setWidget(scrollAreaWidgetContents_2);
        tabWidget->addTab(tab_1, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        scrollArea_6 = new QScrollArea(tab_2);
        scrollArea_6->setObjectName(QStringLiteral("scrollArea_6"));
        scrollArea_6->setGeometry(QRect(370, 0, 341, 371));
        scrollArea_6->setWidgetResizable(true);
        scrollAreaWidgetContents_6 = new QWidget();
        scrollAreaWidgetContents_6->setObjectName(QStringLiteral("scrollAreaWidgetContents_6"));
        scrollAreaWidgetContents_6->setGeometry(QRect(0, 0, 339, 369));
        label_27 = new QLabel(scrollAreaWidgetContents_6);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(10, 10, 81, 16));
        label_28 = new QLabel(scrollAreaWidgetContents_6);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(10, 30, 111, 16));
        pushButton_8 = new QPushButton(scrollAreaWidgetContents_6);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(110, 0, 113, 32));
        pushButton_9 = new QPushButton(scrollAreaWidgetContents_6);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(110, 20, 113, 32));
        textEdit_19 = new QTextEdit(scrollAreaWidgetContents_6);
        textEdit_19->setObjectName(QStringLiteral("textEdit_19"));
        textEdit_19->setGeometry(QRect(110, 60, 61, 16));
        label_29 = new QLabel(scrollAreaWidgetContents_6);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(60, 60, 51, 16));
        label_30 = new QLabel(scrollAreaWidgetContents_6);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(60, 80, 51, 16));
        textEdit_20 = new QTextEdit(scrollAreaWidgetContents_6);
        textEdit_20->setObjectName(QStringLiteral("textEdit_20"));
        textEdit_20->setGeometry(QRect(110, 80, 61, 16));
        pushButton_10 = new QPushButton(scrollAreaWidgetContents_6);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(190, 70, 21, 21));
        scrollArea_6->setWidget(scrollAreaWidgetContents_6);
        scrollArea_3 = new QScrollArea(tab_2);
        scrollArea_3->setObjectName(QStringLiteral("scrollArea_3"));
        scrollArea_3->setGeometry(QRect(0, 0, 371, 371));
        scrollArea_3->setWidgetResizable(true);
        scrollAreaWidgetContents_3 = new QWidget();
        scrollAreaWidgetContents_3->setObjectName(QStringLiteral("scrollAreaWidgetContents_3"));
        scrollAreaWidgetContents_3->setGeometry(QRect(0, 0, 369, 369));
        label_13 = new QLabel(scrollAreaWidgetContents_3);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(170, 50, 51, 16));
        label_14 = new QLabel(scrollAreaWidgetContents_3);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(170, 30, 51, 16));
        label_15 = new QLabel(scrollAreaWidgetContents_3);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(170, 10, 51, 16));
        textEdit_9 = new QTextEdit(scrollAreaWidgetContents_3);
        textEdit_9->setObjectName(QStringLiteral("textEdit_9"));
        textEdit_9->setGeometry(QRect(220, 10, 61, 16));
        textEdit_10 = new QTextEdit(scrollAreaWidgetContents_3);
        textEdit_10->setObjectName(QStringLiteral("textEdit_10"));
        textEdit_10->setGeometry(QRect(220, 30, 61, 16));
        textEdit_11 = new QTextEdit(scrollAreaWidgetContents_3);
        textEdit_11->setObjectName(QStringLiteral("textEdit_11"));
        textEdit_11->setGeometry(QRect(220, 50, 61, 16));
        label_16 = new QLabel(scrollAreaWidgetContents_3);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(20, 90, 81, 16));
        textEdit_12 = new QTextEdit(scrollAreaWidgetContents_3);
        textEdit_12->setObjectName(QStringLiteral("textEdit_12"));
        textEdit_12->setGeometry(QRect(0, 120, 301, 79));
        label_17 = new QLabel(scrollAreaWidgetContents_3);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(10, 210, 51, 16));
        scrollArea_3->setWidget(scrollAreaWidgetContents_3);
        tabWidget->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        scrollArea_4 = new QScrollArea(tab_3);
        scrollArea_4->setObjectName(QStringLiteral("scrollArea_4"));
        scrollArea_4->setGeometry(QRect(0, 0, 371, 371));
        scrollArea_4->setWidgetResizable(true);
        scrollAreaWidgetContents_4 = new QWidget();
        scrollAreaWidgetContents_4->setObjectName(QStringLiteral("scrollAreaWidgetContents_4"));
        scrollAreaWidgetContents_4->setGeometry(QRect(0, 0, 369, 369));
        label_18 = new QLabel(scrollAreaWidgetContents_4);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(170, 50, 51, 16));
        label_19 = new QLabel(scrollAreaWidgetContents_4);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(170, 30, 51, 16));
        label_20 = new QLabel(scrollAreaWidgetContents_4);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(170, 10, 51, 16));
        textEdit_13 = new QTextEdit(scrollAreaWidgetContents_4);
        textEdit_13->setObjectName(QStringLiteral("textEdit_13"));
        textEdit_13->setGeometry(QRect(220, 10, 61, 16));
        textEdit_14 = new QTextEdit(scrollAreaWidgetContents_4);
        textEdit_14->setObjectName(QStringLiteral("textEdit_14"));
        textEdit_14->setGeometry(QRect(220, 30, 61, 16));
        textEdit_15 = new QTextEdit(scrollAreaWidgetContents_4);
        textEdit_15->setObjectName(QStringLiteral("textEdit_15"));
        textEdit_15->setGeometry(QRect(220, 50, 61, 16));
        label_21 = new QLabel(scrollAreaWidgetContents_4);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(20, 90, 81, 16));
        textEdit_16 = new QTextEdit(scrollAreaWidgetContents_4);
        textEdit_16->setObjectName(QStringLiteral("textEdit_16"));
        textEdit_16->setGeometry(QRect(0, 120, 301, 79));
        label_22 = new QLabel(scrollAreaWidgetContents_4);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(10, 210, 51, 16));
        scrollArea_4->setWidget(scrollAreaWidgetContents_4);
        scrollArea_5 = new QScrollArea(tab_3);
        scrollArea_5->setObjectName(QStringLiteral("scrollArea_5"));
        scrollArea_5->setGeometry(QRect(370, 0, 341, 371));
        scrollArea_5->setWidgetResizable(true);
        scrollAreaWidgetContents_5 = new QWidget();
        scrollAreaWidgetContents_5->setObjectName(QStringLiteral("scrollAreaWidgetContents_5"));
        scrollAreaWidgetContents_5->setGeometry(QRect(0, 0, 339, 369));
        label_23 = new QLabel(scrollAreaWidgetContents_5);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(10, 10, 81, 16));
        label_24 = new QLabel(scrollAreaWidgetContents_5);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(10, 30, 111, 16));
        pushButton_5 = new QPushButton(scrollAreaWidgetContents_5);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(110, 0, 113, 32));
        pushButton_6 = new QPushButton(scrollAreaWidgetContents_5);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(110, 20, 113, 32));
        textEdit_17 = new QTextEdit(scrollAreaWidgetContents_5);
        textEdit_17->setObjectName(QStringLiteral("textEdit_17"));
        textEdit_17->setGeometry(QRect(110, 60, 61, 16));
        label_25 = new QLabel(scrollAreaWidgetContents_5);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(60, 60, 51, 16));
        label_26 = new QLabel(scrollAreaWidgetContents_5);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(60, 80, 51, 16));
        textEdit_18 = new QTextEdit(scrollAreaWidgetContents_5);
        textEdit_18->setObjectName(QStringLiteral("textEdit_18"));
        textEdit_18->setGeometry(QRect(110, 80, 61, 16));
        pushButton_7 = new QPushButton(scrollAreaWidgetContents_5);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(190, 70, 21, 21));
        scrollArea_5->setWidget(scrollAreaWidgetContents_5);
        tabWidget->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        scrollArea_7 = new QScrollArea(tab_4);
        scrollArea_7->setObjectName(QStringLiteral("scrollArea_7"));
        scrollArea_7->setGeometry(QRect(0, 0, 371, 371));
        scrollArea_7->setWidgetResizable(true);
        scrollAreaWidgetContents_7 = new QWidget();
        scrollAreaWidgetContents_7->setObjectName(QStringLiteral("scrollAreaWidgetContents_7"));
        scrollAreaWidgetContents_7->setGeometry(QRect(0, 0, 369, 369));
        label_31 = new QLabel(scrollAreaWidgetContents_7);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(170, 50, 51, 16));
        label_32 = new QLabel(scrollAreaWidgetContents_7);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(170, 30, 51, 16));
        label_33 = new QLabel(scrollAreaWidgetContents_7);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(170, 10, 51, 16));
        textEdit_21 = new QTextEdit(scrollAreaWidgetContents_7);
        textEdit_21->setObjectName(QStringLiteral("textEdit_21"));
        textEdit_21->setGeometry(QRect(220, 10, 61, 16));
        textEdit_22 = new QTextEdit(scrollAreaWidgetContents_7);
        textEdit_22->setObjectName(QStringLiteral("textEdit_22"));
        textEdit_22->setGeometry(QRect(220, 30, 61, 16));
        textEdit_23 = new QTextEdit(scrollAreaWidgetContents_7);
        textEdit_23->setObjectName(QStringLiteral("textEdit_23"));
        textEdit_23->setGeometry(QRect(220, 50, 61, 16));
        label_34 = new QLabel(scrollAreaWidgetContents_7);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(20, 90, 81, 16));
        textEdit_24 = new QTextEdit(scrollAreaWidgetContents_7);
        textEdit_24->setObjectName(QStringLiteral("textEdit_24"));
        textEdit_24->setGeometry(QRect(0, 120, 301, 79));
        label_35 = new QLabel(scrollAreaWidgetContents_7);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(10, 210, 51, 16));
        scrollArea_7->setWidget(scrollAreaWidgetContents_7);
        scrollArea_8 = new QScrollArea(tab_4);
        scrollArea_8->setObjectName(QStringLiteral("scrollArea_8"));
        scrollArea_8->setGeometry(QRect(370, 0, 341, 371));
        scrollArea_8->setWidgetResizable(true);
        scrollAreaWidgetContents_8 = new QWidget();
        scrollAreaWidgetContents_8->setObjectName(QStringLiteral("scrollAreaWidgetContents_8"));
        scrollAreaWidgetContents_8->setGeometry(QRect(0, 0, 339, 369));
        label_36 = new QLabel(scrollAreaWidgetContents_8);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(10, 10, 81, 16));
        label_37 = new QLabel(scrollAreaWidgetContents_8);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(10, 30, 111, 16));
        pushButton_11 = new QPushButton(scrollAreaWidgetContents_8);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(110, 0, 113, 32));
        pushButton_12 = new QPushButton(scrollAreaWidgetContents_8);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(110, 20, 113, 32));
        textEdit_25 = new QTextEdit(scrollAreaWidgetContents_8);
        textEdit_25->setObjectName(QStringLiteral("textEdit_25"));
        textEdit_25->setGeometry(QRect(110, 60, 61, 16));
        label_38 = new QLabel(scrollAreaWidgetContents_8);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(60, 60, 51, 16));
        label_39 = new QLabel(scrollAreaWidgetContents_8);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(60, 80, 51, 16));
        textEdit_26 = new QTextEdit(scrollAreaWidgetContents_8);
        textEdit_26->setObjectName(QStringLiteral("textEdit_26"));
        textEdit_26->setGeometry(QRect(110, 80, 61, 16));
        pushButton_13 = new QPushButton(scrollAreaWidgetContents_8);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(190, 70, 21, 21));
        scrollArea_8->setWidget(scrollAreaWidgetContents_8);
        tabWidget->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        scrollArea_9 = new QScrollArea(tab_5);
        scrollArea_9->setObjectName(QStringLiteral("scrollArea_9"));
        scrollArea_9->setGeometry(QRect(0, 0, 371, 371));
        scrollArea_9->setWidgetResizable(true);
        scrollAreaWidgetContents_9 = new QWidget();
        scrollAreaWidgetContents_9->setObjectName(QStringLiteral("scrollAreaWidgetContents_9"));
        scrollAreaWidgetContents_9->setGeometry(QRect(0, 0, 369, 369));
        label_40 = new QLabel(scrollAreaWidgetContents_9);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(170, 50, 51, 16));
        label_41 = new QLabel(scrollAreaWidgetContents_9);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(170, 30, 51, 16));
        label_42 = new QLabel(scrollAreaWidgetContents_9);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(170, 10, 51, 16));
        textEdit_27 = new QTextEdit(scrollAreaWidgetContents_9);
        textEdit_27->setObjectName(QStringLiteral("textEdit_27"));
        textEdit_27->setGeometry(QRect(220, 10, 61, 16));
        textEdit_28 = new QTextEdit(scrollAreaWidgetContents_9);
        textEdit_28->setObjectName(QStringLiteral("textEdit_28"));
        textEdit_28->setGeometry(QRect(220, 30, 61, 16));
        textEdit_29 = new QTextEdit(scrollAreaWidgetContents_9);
        textEdit_29->setObjectName(QStringLiteral("textEdit_29"));
        textEdit_29->setGeometry(QRect(220, 50, 61, 16));
        label_43 = new QLabel(scrollAreaWidgetContents_9);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(20, 90, 81, 16));
        textEdit_30 = new QTextEdit(scrollAreaWidgetContents_9);
        textEdit_30->setObjectName(QStringLiteral("textEdit_30"));
        textEdit_30->setGeometry(QRect(0, 120, 301, 79));
        label_44 = new QLabel(scrollAreaWidgetContents_9);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(10, 210, 51, 16));
        scrollArea_9->setWidget(scrollAreaWidgetContents_9);
        scrollArea_10 = new QScrollArea(tab_5);
        scrollArea_10->setObjectName(QStringLiteral("scrollArea_10"));
        scrollArea_10->setGeometry(QRect(370, 0, 341, 371));
        scrollArea_10->setWidgetResizable(true);
        scrollAreaWidgetContents_10 = new QWidget();
        scrollAreaWidgetContents_10->setObjectName(QStringLiteral("scrollAreaWidgetContents_10"));
        scrollAreaWidgetContents_10->setGeometry(QRect(0, 0, 339, 369));
        label_45 = new QLabel(scrollAreaWidgetContents_10);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(10, 10, 81, 16));
        label_46 = new QLabel(scrollAreaWidgetContents_10);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(10, 30, 111, 16));
        pushButton_14 = new QPushButton(scrollAreaWidgetContents_10);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(110, 0, 113, 32));
        pushButton_15 = new QPushButton(scrollAreaWidgetContents_10);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));
        pushButton_15->setGeometry(QRect(110, 20, 113, 32));
        textEdit_31 = new QTextEdit(scrollAreaWidgetContents_10);
        textEdit_31->setObjectName(QStringLiteral("textEdit_31"));
        textEdit_31->setGeometry(QRect(110, 60, 61, 16));
        label_47 = new QLabel(scrollAreaWidgetContents_10);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(60, 60, 51, 16));
        label_48 = new QLabel(scrollAreaWidgetContents_10);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(60, 80, 51, 16));
        textEdit_32 = new QTextEdit(scrollAreaWidgetContents_10);
        textEdit_32->setObjectName(QStringLiteral("textEdit_32"));
        textEdit_32->setGeometry(QRect(110, 80, 61, 16));
        pushButton_16 = new QPushButton(scrollAreaWidgetContents_10);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(190, 70, 21, 21));
        scrollArea_10->setWidget(scrollAreaWidgetContents_10);
        tabWidget->addTab(tab_5, QString());
        textEdit_6 = new QTextEdit(centralWidget);
        textEdit_6->setObjectName(QStringLiteral("textEdit_6"));
        textEdit_6->setGeometry(QRect(10, 440, 31, 16));
        MainWindow->setCentralWidget(centralWidget);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(4);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0));
        label->setText(QApplication::translate("MainWindow", "Bienvenue\357\274\201", 0));
        pushButton->setText(QApplication::translate("MainWindow", "Panier", 0));
        label_2->setText(QApplication::translate("MainWindow", "plats choisis", 0));
        label_3->setText(QApplication::translate("MainWindow", "euros", 0));
        label_6->setText(QApplication::translate("MainWindow", "Calorie:", 0));
        label_5->setText(QApplication::translate("MainWindow", "Saveur:", 0));
        label_4->setText(QApplication::translate("MainWindow", "Nom:", 0));
        label_7->setText(QApplication::translate("MainWindow", "Description:", 0));
        label_8->setText(QApplication::translate("MainWindow", "Note", 0));
        label_9->setText(QApplication::translate("MainWindow", "P\303\251r\303\251rence:", 0));
        label_10->setText(QApplication::translate("MainWindow", "Ne mange pas:", 0));
        pushButton_2->setText(QApplication::translate("MainWindow", "+Ajouter", 0));
        pushButton_3->setText(QApplication::translate("MainWindow", "+Ajouter", 0));
        label_11->setText(QApplication::translate("MainWindow", "Nom:", 0));
        label_12->setText(QApplication::translate("MainWindow", "\303\251toiles:", 0));
        pushButton_4->setText(QApplication::translate("MainWindow", "+", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_1), QApplication::translate("MainWindow", "plat du jour", 0));
        label_27->setText(QApplication::translate("MainWindow", "P\303\251r\303\251rence:", 0));
        label_28->setText(QApplication::translate("MainWindow", "Ne mange pas:", 0));
        pushButton_8->setText(QApplication::translate("MainWindow", "+Ajouter", 0));
        pushButton_9->setText(QApplication::translate("MainWindow", "+Ajouter", 0));
        label_29->setText(QApplication::translate("MainWindow", "Nom:", 0));
        label_30->setText(QApplication::translate("MainWindow", "\303\251toiles:", 0));
        pushButton_10->setText(QApplication::translate("MainWindow", "+", 0));
        label_13->setText(QApplication::translate("MainWindow", "Calorie:", 0));
        label_14->setText(QApplication::translate("MainWindow", "Saveur:", 0));
        label_15->setText(QApplication::translate("MainWindow", "Nom:", 0));
        label_16->setText(QApplication::translate("MainWindow", "Description:", 0));
        label_17->setText(QApplication::translate("MainWindow", "Note", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("MainWindow", "entr\303\251e", 0));
        label_18->setText(QApplication::translate("MainWindow", "Calorie:", 0));
        label_19->setText(QApplication::translate("MainWindow", "Saveur:", 0));
        label_20->setText(QApplication::translate("MainWindow", "Nom:", 0));
        label_21->setText(QApplication::translate("MainWindow", "Description:", 0));
        label_22->setText(QApplication::translate("MainWindow", "Note", 0));
        label_23->setText(QApplication::translate("MainWindow", "P\303\251r\303\251rence:", 0));
        label_24->setText(QApplication::translate("MainWindow", "Ne mange pas:", 0));
        pushButton_5->setText(QApplication::translate("MainWindow", "+Ajouter", 0));
        pushButton_6->setText(QApplication::translate("MainWindow", "+Ajouter", 0));
        label_25->setText(QApplication::translate("MainWindow", "Nom:", 0));
        label_26->setText(QApplication::translate("MainWindow", "\303\251toiles:", 0));
        pushButton_7->setText(QApplication::translate("MainWindow", "+", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("MainWindow", "plat", 0));
        label_31->setText(QApplication::translate("MainWindow", "Calorie:", 0));
        label_32->setText(QApplication::translate("MainWindow", "Saveur:", 0));
        label_33->setText(QApplication::translate("MainWindow", "Nom:", 0));
        label_34->setText(QApplication::translate("MainWindow", "Description:", 0));
        label_35->setText(QApplication::translate("MainWindow", "Note", 0));
        label_36->setText(QApplication::translate("MainWindow", "P\303\251r\303\251rence:", 0));
        label_37->setText(QApplication::translate("MainWindow", "Ne mange pas:", 0));
        pushButton_11->setText(QApplication::translate("MainWindow", "+Ajouter", 0));
        pushButton_12->setText(QApplication::translate("MainWindow", "+Ajouter", 0));
        label_38->setText(QApplication::translate("MainWindow", "Nom:", 0));
        label_39->setText(QApplication::translate("MainWindow", "\303\251toiles:", 0));
        pushButton_13->setText(QApplication::translate("MainWindow", "+", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("MainWindow", "dessert", 0));
        label_40->setText(QApplication::translate("MainWindow", "Calorie:", 0));
        label_41->setText(QApplication::translate("MainWindow", "Saveur:", 0));
        label_42->setText(QApplication::translate("MainWindow", "Nom:", 0));
        label_43->setText(QApplication::translate("MainWindow", "Description:", 0));
        label_44->setText(QApplication::translate("MainWindow", "Note", 0));
        label_45->setText(QApplication::translate("MainWindow", "P\303\251r\303\251rence:", 0));
        label_46->setText(QApplication::translate("MainWindow", "Ne mange pas:", 0));
        pushButton_14->setText(QApplication::translate("MainWindow", "+Ajouter", 0));
        pushButton_15->setText(QApplication::translate("MainWindow", "+Ajouter", 0));
        label_47->setText(QApplication::translate("MainWindow", "Nom:", 0));
        label_48->setText(QApplication::translate("MainWindow", "\303\251toiles:", 0));
        pushButton_16->setText(QApplication::translate("MainWindow", "+", 0));
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QApplication::translate("MainWindow", "Boisson", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
